master <- wishlist
ForBestClients/grandus-frontend-lib pull request #62
Opened 2021-04-01 11:57 UTC by rasevp

wishlist pre neprihlasenych

**Potrebny BE**

2021-04-08 10:20 UTC, ivankopcik requested changes
je tam bug, s tym mutateCompare

2021-04-08 10:20 UTC, ivankopcik commented on hooks/useWishlist.js
> +    mutateCompare: mutate,
tu asi nema byt mutateCompare nie?

2021-04-08 10:20 UTC, ivankopcik commented on utils/transformers.js
> +    products: get(object, "items", []),
toto je spatne kompatibilne?

2021-04-09 07:07 UTC, rasevp commented on hooks/useWishlist.js
> +    mutateCompare: mutate,
upravene

2021-04-09 07:10 UTC, rasevp commented on utils/transformers.js
> +    products: get(object, "items", []),
no cely novy wishlist je potrebne premergovat do projektov cez `mastra`, pretoze sa upravoval aj `pages/wishlist/index.js` v `grandus-front-v3` (https://github.com/ForBestClients/grandus-frontend-v3/pull/396) takze stary globalne nebude fungovat

2021-06-11 09:41 UTC, merged